# Generated by Django 5.2.1 on 2025-05-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('genres', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('user_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('condition', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'db_table': 'user_books',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('user_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.userbook')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
